FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y curl gnupg lsb-release ca-certificates git

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

RUN apt-get update && apt-get install -y docker.io

USER jenkins